# ssh-keyscan gitlab.com >> authorized_keys: use this command to add gitlab ssh keys to sever. Run on server terminal
# cat ~/.ssh/id_rsa.pub >> authorized_keys : Run this command on the sever on the terminal. 
# Both COMMANDS ABOVE ARE necessary.
# Have to put .env echo statments in Docker build stage because documents dont persist. Artifacts could be used.

stages:
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA


build-App:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - echo   "REACT_APP_ServiceId=$REACT_APP_ServiceId" >> .env
    - echo   "REACT_APP_TemplateId=$REACT_APP_TemplateId" >> .env
    - echo   "REACT_APP_UserId=$REACT_APP_UserId" >> .env
    - echo   "REACT_APP_apiKey=$REACT_APP_apiKey" >> .env
    - echo   "REACT_APP_authDomain=$REACT_APP_authDomain" >> .env
    - echo   "REACT_APP_projectId=$REACT_APP_projectId" >> .env
    - echo   "REACT_APP_storageBucket=$REACT_APP_storageBucket" >> .env
    - echo   "REACT_APP_messagingSenderId=$REACT_APP_messagingSenderId" >> .env
    - echo   "REACT_APP_appId=$REACT_APP_appId" >> .env
    - echo   "REACT_APP_measurementId=$REACT_APP_measurementId" >> .env
    - cat .env
    - docker build . -t $TAG_COMMIT -t $TAG_LATEST 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - master

deploy-1:
  image: ubuntu:latest
  stage: deploy
  tags:
    - deployment-backup
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/*
  - chmod 644 ~/.ssh/*.pub
  - ssh-add
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - ls -ld ~/.ssh/*
  script:
    - ssh   -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
    - ssh  -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8080:8080 --name my-app $TAG_COMMIT"
  environment:
    name: production
    url: http://159.203.115.184
  only:
    - master
